name: flutter_sp_social
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  pretty_qr_code: ^3.0.0
  crypto: ^3.0.3
  google_fonts: any
  file_picker: ^6.1.1
  carousel_slider: ^4.2.1
  easy_web_view: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - data/
    - static/