name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-example:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # atualizado

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.16.7

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4 # atualizado

      - name: Build project
        run: flutter build web --no-source-maps --base-href /flutter_sp_social/ --web-renderer html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # atualizado
        with:
          path: './build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 # atualizado
